      SUBROUTINE DFLUX(FLUX,SOL,KSTEP,KINC,TIME,NOEL,NPT,
     1 COORDS,JLTYP,TEMP,PRESS,SNAME)
      INCLUDE 'ABA_PARAM.INC'
      DIMENSION FLUX(2),TIME(2),COORDS(3)
      CHARACTER*80 SNAME
      FLUX(1)=1000.0D0
      FLUX(2)=0.0D0
      RETURN
      END
