      SUBROUTINE DISP(U,KSTEP,KINC,TIME,NODE,NOEL,JDOF,COORDS)
      INCLUDE 'ABA_PARAM.INC'
      DIMENSION U(3),TIME(3),COORDS(3)
      U(1)=0.1D0*TIME(1)
      U(2)=0.1D0
      U(3)=0.0D0
      RETURN
      END
