      SUBROUTINE FILM(H,SINK,TEMP,KSTEP,KINC,TIME,NOEL,NPT,
     1 COORDS,JLTYP,FIELD,NFIELD,SNAME,NODE,AREA)
      INCLUDE 'ABA_PARAM.INC'
      DIMENSION H(2),TIME(2),COORDS(3),FIELD(NFIELD)
      CHARACTER*80 SNAME
      H(1)=100.0D0
      H(2)=0.0D0
      SINK=20.0D0
      RETURN
      END
