      SUBROUTINE UEXPAN(EXPAN,DEXPANDT,TEMP,TIME,DTIME,PREDEF,
     1 DPRED,STATEV,CMNAME,NSTATV,IARRAY)
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      DIMENSION EXPAN(*),DEXPANDT(*),TEMP(2),TIME(2),PREDEF(*)
      DIMENSION DPRED(*),STATEV(NSTATV),IARRAY(3)
      EXPAN(1)=1.0D-5*TEMP(2)
      DEXPANDT(1)=1.0D-5
      RETURN
      END
